server:
  port: 8888
  
spring:
  application:
    name: msvc-configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CsarNarciso/Microservices-Spring-Boot
          defaultLabel: master
          search-paths: 
            - Configs