services:
  msvc-gateaway:
    build: ./Gateaway
    ports: 
      - "8000:8000"
    networks:
      - eureka-net
    depends_on:
      msvc-eureka:
        condition: service_healthy
      msvc-config:
        condition: service_healthy
      msvc-books:
        condition: service_healthy
      msvc-editorials:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8000/actuator/health"]
      start_period: 40s
      interval: 20s
      timeout: 5s
      retries: 5
  msvc-books:
    build: ./Books
    ports: 
      - "8001:8001"
    networks:
      - eureka-net	
    depends_on:
      msvc-eureka:
        condition: service_healthy
      msvc-config:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8001/actuator/health"]
      start_period: 40s
      interval: 20s
      timeout: 5s
      retries: 5
  msvc-config:
    build: ./Config
    ports:
      - "8888:8888"
    networks:
      - eureka-net
    depends_on:
      msvc-eureka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8888/actuator/health"]
      start_period: 40s
      interval: 20s
      timeout: 5s
      retries: 5
  msvc-eureka:
    build: ./Eureka
    ports:
      - "8761:8761"
    networks:
      - eureka-net	  
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8761/actuator/health"]
      start_period: 40s
      interval: 20s
      timeout: 5s
      retries: 5
  postgres-db:
    container_name: postgres-db-c
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=letmein
    networks:
      - postgres-db-net
    volumes:
      - postgres-db-vol:/data/postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "db", "-U", "postgres"]
      start_period: 40s
      interval: 20s
      timeout: 5s
      retries: 5
networks:
  eureka-net:
  postgres-db-net: 
    driver: bridge
volumes:
  postgres-db-vol:


