version: "3"
services:
  gateaway:
    build: ./Gateaway
    ports: 
      - "8080:8080"
    depends_on:
      - config
      - gateaway
  books:
    build: ./Books
    ports: 
      - "8001:8001"
    depends_on:
      - config
      - gateaway
      - mysqldb
  genres:
    build: ./Genres
    ports:
      - "8002:8002"
    depends_on:
      - config
      - gateaway
      - mysqldb
  eureka:
    build: ./Eureka
    ports:
      - ""
  config:
    build: ./Config
    ports:
      - ""
    depends_on:
      - eureka   
  mysqldb:
    image: mysql
    enviroment:
     - MYSQL_ROOT_PASSWORD=letmein
     - MYSQL_DATABASE=microservices-project-db
