services:
  msvc-config:
    image: csarnar/microservices-spring-boot-msvc-config
    ports:
      - "8888:8888"
    networks:
      - eureka-net
    depends_on:
      msvc-eureka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8888/actuator/health"]
      start_period: 40s
      interval: 20s
      timeout: 5s
      retries: 5

