services:
  msvc-editorials:
    build: ./Editorials
    ports:
      - "8002:8002"
    networks:
      - eureka-net
      - postgres-db-net	
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
    depends_on:
      postgres-db:
        condition: service_healthy
      msvc-config:
        condition: service_healthy
      msvc-eureka:
        condition: service_healthy
      msvc-books:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8002/actuator/health"]
      start_period: 40s
      interval: 20s
      timeout: 5s
      retries: 5

