services:
  msvc-eureka:
    image: csarnar/microservices-spring-boot-msvc-eureka
    ports:
      - "8761:8761"
    networks:
      - eureka-net	  
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8761/actuator/health"]
      start_period: 40s
      interval: 20s
      timeout: 5s
      retries: 5

