services:
  msvc-gateaway:
    image: csarnar/microservices-spring-boot-msvc-gateaway
    ports: 
      - "8000:8000"
    networks:
      - eureka-net
    depends_on:
      msvc-eureka:
        condition: service_healthy
      msvc-config:
        condition: service_healthy
      msvc-books:
        condition: service_healthy
      msvc-editorials:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8000/actuator/health"]
      start_period: 40s
      interval: 20s
      timeout: 5s
      retries: 5

