services:
  postgres-db:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - postgres-db-net
    volumes:
      - postgres-db-vol:/data/postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "db", "-U", "postgres"]
      start_period: 40s
      interval: 20s
      timeout: 5s
      retries: 5

