spring:
  application:
    name: msvc-books

  config:
    import: optional:configserver:lb://msvc-configServer
  
  cloud:
    config:
      discovery:
        enabled: true  
        serviceId: msvc-configServer
    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: 
      defaultZone: http://msvc-eureka:8761/eureka/