spring:
  application:
    name: msvc-gateway
  
  config:
    import: optional:configserver:lb://msvc-configServer
  
  cloud:
    config:
      discovery:
        serviceId: msvc-configServer
        enabled: true  
    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: 
      defaultZone: http://msvc-eureka:8761/eureka/