spring:
  application:
    name: msvc-editorials
    
  config:
    import: optional:configserver:lb://msvc-configServer
  
  cloud:
    config:
      discovery:
        serviceId: msvc-configServer
        enabled: true

eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
