server:
  port: 8000

spring:
  application:
    name: msvc-gateway
  cloud:
    config:
      discovery:
        serviceId: msvc-configServer
        enabled: true  
 
eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
  