spring:
  application:
    name: msvc-books
  cloud:
    config:
      discovery:
        serviceId: msvc-configServer
        enabled: true  
  config:
    import: optional:configserver:lb://msvc-configServer
    
    
eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/