spring:
  application:
    name: msvc-editorials
    
  config:
    import: optional:configserver:lb://msvc-configServer
  
  cloud:
    config:
      discovery:
        serviceId: msvc-configServer
        enabled: true
#Postgres database
  datasource:
    driverClassName: org.postgresql.Driver 
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format-sql: true 
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: 
      defaultZone: http://msvc-eureka:8761/eureka/
